# This is a basic workflow to help you get started with Actions

name: deploy gh-pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  name: Build and deploy gh-pages
  env:
    MY_SECRET   : ${{secrets.cd_secret}}
    USER_NAME   : frankkiv
    USER_EMAIL  : frankkiv@github.com
    PUBLISH_DIR : ./dist
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [10.x]
  steps:
  - uses: actions/checkout@v1
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
  - name: npm install
    run: |
      npm install
  - name: npm run deploy
    run: |
      npm run deploy
